version: '3'

networks:
    laravel:


services:
    webserver:
        container_name: purchases_system_webserver
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/project:delegated
        depends_on:
            - php
            - database_server
        networks:
            - laravel

    database_server:
        container_name: purchases_system_database
        image: mariadb:10.6
        restart: unless-stopped
        volumes:
            - ./storage/app/mysql:/var/lib/mysql
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: purchases_system
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    phpmyadmin:
        container_name: purchases_system_phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - database_server
        environment:
            PMA_HOST: database_server
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        networks:
            - laravel


    php:
        container_name: purchases_system_php
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html/project:delegated
        networks:
            - laravel

    composer:
        container_name: purchases_system_composer
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - .:/var/www/html/project
        depends_on:
            - php
        entrypoint: [ 'composer' ]
        networks:
            - laravel

    artisan:
        container_name: purchases_system_artisan
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - .:/var/www/html/project:delegated
        depends_on:
            - database_server
        entrypoint: [ 'php', '/var/www/html/project/artisan' ]
        networks:
            - laravel

